// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjslwgukffhkmdzryguz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqc2x3Z3VrZmZoa21kenJ5Z3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDk0MjEsImV4cCI6MjA1NTk4NTQyMX0.UHUwK7DApeA05dIjxRlq-r1zlvsGCItUoYDSy02TFss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);